#!/bin/bash

# Unfortunately, Codespaces doesn't have a way to open a default .code-workspace file,
# see https://github.com/microsoft/vscode-remote-release/issues/3665
file_path="/workspaces/.codespaces/.persistedshare/.workspace-opened"
dotfiles_dir="/workspaces/.codespaces/.persistedshare/dotfiles"

if [ ! -f "$file_path" ]; then
  if [ -d "/workspaces/github" ] && [ -d "/workspaces/github-ui" ] && [ -d "$dotfiles_dir" ]; then
    if command -v code >/dev/null 2>&1; then
      touch "$file_path"
      echo "==> First run, loading workspace..."
      code --reuse-window $dotfiles_dir/with-github-ui.code-workspace
    else
      echo "==> VS Code command not found, unable to open workspace."
    fi
  fi
elif [ -f "$file_path" ]; then
  echo "==> $file_path exists, workspace already opened."
fi
